# This file is the blueprint for deploying the Yeab Game Zone on Render.
# It defines the services, database, and environment variables needed.
# Place this file in the root directory of your project.

services:
  # A web service for the FastAPI webhook server. This service receives updates
  # from Telegram and payment notifications from Chapa.
  - type: web
    name: yeab-game-zone-api
    env: python
    # You can change the plan to a paid one for better performance
    plan: free 
    # The command to install dependencies and set up the initial database schema.
    buildCommand: "pip install -r requirements.txt && python -c 'import asyncio; from db.manager import create_db_pool, setup_database; async def main(): pool = await create_db_pool(); await setup_database(pool); await pool.close(); asyncio.run(main()); print(\"Database setup complete.\")'"
    # The command to start the web server. Gunicorn runs Uvicorn workers for FastAPI.
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT api.main:app"
    # Render uses this path to check if the service is running correctly.
    healthCheckPath: /
    envVars:
      # These are the secret keys you need to set in the Render dashboard.
      # Go to Environment -> Add Secret File or Add Environment Variable.
      - key: TELEGRAM_BOT_TOKEN
        sync: false # 'sync: false' means you must set this value in the Render UI.
      - key: CHAPA_API_KEY
        sync: false
      - key: ADMIN_TELEGRAM_ID # Your personal Telegram ID for notifications.
        sync: false
        
      # These variables are automatically configured by Render based on the other services.
      # You DO NOT need to set these manually.
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-game-zone-db # Must match the database name below
          property: connectionString
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: yeab-game-zone-api # Must match this service's name
          property: url

databases:
  # A managed PostgreSQL database instance for storing all application data.
  - name: yeab-game-zone-db
    # You can change the plan for more storage and performance.
    plan: free 
    databaseName: yeab_game_zone_db
    user: yeab_game_zone_user