services:
  - type: web
    name: yeab-game-zone-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT api.main:app"
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAPA_API_KEY
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-game-zone-db
          property: connectionString
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: yeab-game-zone-api
          property: url

databases:
  - name: yeab-game-zone-db
    plan: free
    databaseName: yeab_game_zone_db
    user: yeab_game_zone_user